install_dnf_packages: true
# Packages that can be installed from dnf without any extra configuration
dnf_packages:
  - git
  - openssl
  - python3
  - python3-pip
  - curl
  - wget
  - ripgrep
  - unzip
  - source-foundry-hack-fonts
  - dconf-editor # GUI for gnome configs
  - cmake
  - gcc
  - vim
  - xclip
  - golang
  - dotnet-sdk-8.0
  - flatpak
  - nodejs

install_zsh: true
zsh_default_shell: true

install_kitty: true

install_rust: true

install_docker: true

install_flatpak_apps: true

install_vscode: true
vscode_extensions:
  - rust-lang.rust-analyzer
  - ms-vscode-remote.remote-containers
  - dracula-theme.theme-dracula
  - jdinhlife.gruvbox
  - vscodevim.vim
  - ms-dotnettools.vscode-dotnet-runtime
  - ms-dotnettools.csharp
  - ms-azuretools.vscode-docker
  - yzhang.markdown-all-in-one
  - charliermarsh.ruff
  - redhat.vscode-yaml
  - ms-python.vscode-pylance
  - ms-python.python
  - ms-python.debugpy
  - ms-python.mypy-type-checker

install_virtualbox: true
