install_dnf_packages: true
dnf_packages:
  - git
  - openssl
  - python3-pip
  - curl
  - wget
  - ripgrep
  - unzip
  - source-foundry-hack-fonts
  - dconf-editor # GUI for gnome configs
  - cmake
  - gcc
  - vim
  - xclip
  - dnf-plugins-core # Required for Docker
  - golang
  - rustup
  - dotnet-sdk-8.0
  - fedora-workstation-repositories # Required for google-chrome
  - flatpak

install_zsh: true
zsh_default_shell: true

install_kitty: true
